# Generated by Django 5.1 on 2024-08-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Где выполнять?",
                        max_length=100,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Во сколько выполнять?",
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Что делать?", max_length=200, verbose_name="Действие"
                    ),
                ),
                (
                    "is_nice_habit",
                    models.BooleanField(
                        choices=[(True, "Да"), (False, "Нет")],
                        default=False,
                        help_text="Это приятна привычка?",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("in a day", "Через день"),
                            ("in a two days", "Раз в три дня"),
                            ("weekly", "Раз в неделю"),
                        ],
                        default="Ежедневно",
                        help_text="Как часто выполнять?",
                        max_length=50,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Какая награда?",
                        max_length=150,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Введите время на выполнение не более 120 сек.",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичность"),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
